name: eggcounting
channels:
  - conda-forge
  - defaults
dependencies:
  - fire=0.3.1
  - numpy=1.18.5
  - opencv=4.3.0
  - pandas=1.0.5
  - pyqt=5.12.3
  - pytables=3.6.1
  - python=3.8.3
  - tqdm=4.50.2
  - pip:
    - imgstore==0.2.9
